import CampaignsTable from '../../components/DataTable/CampaignsTable'
import '../dashboard/dashboard.scss'
import '../../fullpage.scss'

import { React } from 'react'
import Sidemenu from '../../components/Sidemenu/Sidemenu'
import Card from '../../components/Card'
import Icon from '../../components/Icon/Icon'
import Button from '../../components/Button'
import Stat from '../../components/Stat/Stat'
import ButtonGroup from '../../components/ButtonGroup'
import './campaigns.scss'
import InputText from '../../components/InputText/InputText'
import PageHeader from '../../components/PageHeader/PageHeader'

const account = {
	name: 'Cobalt Fairy',
	plan: 'Free Plan',
}
const user = {
	name: 'Cobalt Fairy',
	email: 'cf@fairymail.app',
}
const getNameInitials = (name) =>
	name
		.split(' ')
		.map((word) => word[0].toUpperCase())
		.join('')
const stats = [
	{
		label: 'Emails Sent',
		value: '752',
		percentage: -12,
		defaultValue: false, // This will be the default selected option
	},
	{
		label: 'Totals Clicks',
		value: '159',
		percentage: 17,
		defaultValue: false,
	},
	{
		label: 'Total Opens',
		value: '340',
		percentage: 19,
		defaultValue: false,
	},
	{
		label: 'Spam',
		value: '85',
		percentage: 5,
		defaultValue: false,
	},
]
const subs_stats = [
	{
		label: 'Total',
		value: '752',
		default: false,
		percentage: 5,
	},
	{
		label: 'Unsubscribed',
		value: '159',
		default: true,
		percentage: 5,
	},
]

	const campaigns = [
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
	]

const Campaigns = () => {
	return (
		<>
			<div className="fm-page-wrapper">
				<Sidemenu />
				<div className="fm-page-container">
					<PageHeader user={user} account={account}/>
					<div className="page-name-container">
						<div className="page-name">Campaigns</div>
						<Button icon={'Plus'} type="action">
							New Campaign
						</Button>
					</div>
					<div className="filters-container">
						<div className="row">
							<ButtonGroup
								value="today"
								options={[
									{ value: 'today', label: 'Sent (2)' },
									{ value: '7days', label: 'Draft (1)' },
									{ value: '30days', label: 'Outbox (0)' },
									{ value: 'all', label: 'Templates (4)' },
								]}
								onChange={(value) => {
									console.log(value)
								}}
							></ButtonGroup>
						</div>
						<div className="row d-flex content-space-between">
							<InputText style={{ width: '85%' }} placeholder="Search Campaign" label="Search Campaign" hasError={false} errorMessage="Name must be at least 3 characters long." />
							<Button type="secondary" icon={'Filters'}>
								Filters
							</Button>
						</div>
					</div>

                    <div className="">
					<CampaignsTable campaigns={campaigns} />
					</div>
				</div>
			</div>
		</>
	)
}

export default Campaigns
