import CampaignsTable from '../../components/DataTable/CampaignsTable'
import '../dashboard/dashboard.scss'
import '../../fullpage.scss'

import { React, useEffect, useState } from 'react'
import Sidemenu from '../../components/Sidemenu/Sidemenu'
import Card from '../../components/Card'
import Icon from '../../components/Icon/Icon'
import Button from '../../components/Button'
import Stat from '../../components/Stat/Stat'
import ButtonGroup from '../../components/ButtonGroup'
import './campaigns.scss'
import InputText from '../../components/InputText/InputText'
import PageHeader from '../../components/PageHeader/PageHeader'
import User from '../../service/User'
import { ApiService } from '../../service/api-service'
import PopupText from '../../components/PopupText/PopupText'

const account = {
	name: 'Cobalt Fairy',
	plan: 'Free Plan',
}
const user = {
	name: 'Cobalt Fairy',
	email: 'cf@fairymail.app',
}
const getNameInitials = (name) =>
	name
		.split(' ')
		.map((word) => word[0].toUpperCase())
		.join('')
const stats = [
	{
		label: 'Emails Sent',
		value: '752',
		percentage: -12,
		defaultValue: false, // This will be the default selected option
	},
	{
		label: 'Totals Clicks',
		value: '159',
		percentage: 17,
		defaultValue: false,
	},
	{
		label: 'Total Opens',
		value: '340',
		percentage: 19,
		defaultValue: false,
	},
	{
		label: 'Spam',
		value: '85',
		percentage: 5,
		defaultValue: false,
	},
]
const subs_stats = [
	{
		label: 'Total',
		value: '752',
		default: false,
		percentage: 5,
	},
	{
		label: 'Unsubscribed',
		value: '159',
		default: true,
		percentage: 5,
	},
]

const campaigns2 = [
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'User-friendly transitional pricing structure',
		recipients: 39121,
		opens: '65%',
		clicks: '93%',
		type: 'SMS',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synergistic tangible groupware',
		recipients: 25946,
		opens: '40%',
		clicks: '68%',
		type: 'Social Media',
		date: '2025-01-01',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Front-line even-keeled encryption',
		recipients: 36302,
		opens: '21%',
		clicks: '76%',
		type: 'Email',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Re-contextualized regional intranet',
		recipients: 45039,
		opens: '84%',
		clicks: '83%',
		type: 'Email',
		date: '2025-01-07',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered secondary firmware',
		recipients: 44327,
		opens: '6%',
		clicks: '8%',
		type: 'SMS',
		date: '2025-01-06',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Multi-tiered logistical matrices',
		recipients: 27215,
		opens: '53%',
		clicks: '41%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Configurable heuristic Graphical User Interface',
		recipients: 48929,
		opens: '89%',
		clicks: '54%',
		type: 'Social Media',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Fully-configurable methodical encryption',
		recipients: 18191,
		opens: '92%',
		clicks: '24%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Synchronised background parallelism',
		recipients: 17750,
		opens: '14%',
		clicks: '77%',
		type: 'Email',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Extended bi-directional workforce',
		recipients: 12643,
		opens: '73%',
		clicks: '87%',
		type: 'SMS',
		date: '2025-01-09',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Managed 24/7 functionalities',
		recipients: 10436,
		opens: '32%',
		clicks: '49%',
		type: 'Push Notification',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Reduced cohesive system engine',
		recipients: 39408,
		opens: '17%',
		clicks: '33%',
		type: 'Social Media',
		date: '2025-01-05',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Optional reciprocal flexibility',
		recipients: 36710,
		opens: '96%',
		clicks: '81%',
		type: 'Push Notification',
		date: '2025-01-08',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Devolved impactful task-force',
		recipients: 40386,
		opens: '81%',
		clicks: '63%',
		type: 'Email',
		date: '2025-01-13',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Robust discrete throughput',
		recipients: 18697,
		opens: '28%',
		clicks: '34%',
		type: 'SMS',
		date: '2025-01-02',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Sharable user-facing matrices',
		recipients: 41662,
		opens: '35%',
		clicks: '59%',
		type: 'Push Notification',
		date: '2025-01-11',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Triple-buffered incremental interface',
		recipients: 47389,
		opens: '48%',
		clicks: '21%',
		type: 'Social Media',
		date: '2025-01-12',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Distributed human-resource solution',
		recipients: 26709,
		opens: '64%',
		clicks: '88%',
		type: 'Email',
		date: '2025-01-03',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Function-based directional toolset',
		recipients: 31396,
		opens: '25%',
		clicks: '75%',
		type: 'SMS',
		date: '2025-01-10',
		actions: 'Actions Component Placeholder',
	},
	{
		image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
		name: 'Decentralized maximized knowledge user',
		recipients: 21871,
		opens: '71%',
		clicks: '52%',
		type: 'Push Notification',
		date: '2025-01-04',
		actions: 'Actions Component Placeholder',
	},
]

const Campaigns = () => {
	const [campaigns1, setCampaigns1] = useState([])
	const [account, setAccount] = useState({})
	const [searchTerm, setSearchTerm] = useState('')
	const [loading, setLoading] = useState(true)
	const [itemsPerPage, setItemsPerPage] = useState(50)
	const [currentPage, setCurrentPage] = useState(1)
	const [skeletons] = useState([{}, {}, {}, {}, {}, {}, {}, {}, {}])
	const [campaigns, setCampaigns] = useState([])
	const [cmpStatus, setCmpStatus] = useState('sent')
	const [meta, setMeta] = useState([])
	const [error, setError] = useState(null)
	const [domainVerified, setDomainVerified] = useState(true)
	const [dkimVerified, setDkimVerified] = useState(true)
	const [emailVerified, setEmailVerified] = useState(true)
	const [selectedCampaignType, setSelectedCampaignType] = useState('sent')

	const [user2, setUser2] = useState()

	const [filteredCampaigns, setFilteredCampaigns] = useState([])
	const campaignsTableData = filteredCampaigns.map((campaign) => {
		return {
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: campaign.name,
			recipients: campaign.recipients,
			opens: campaign?.stats?.o,
			clicks: campaign?.stats?.c,
			type: campaign.type === 'absplit' ? 'AB Split' : 'Normal',
			date: campaign.date,
			actions: campaign.actions,
			uuid: campaign.uuid,
			account: campaign?.account?.id,
			recp_groups: [...campaign.recp_groups],
		}
	})

	const totalCampaignsSent = campaigns.filter((campaign) => campaign.status === 'sent').length
	const totalCampaignsDraft = campaigns.filter((campaign) => campaign.status === 'draft').length
	const totalCampaignsOutBox = campaigns.filter((campaign) => campaign.status === 'outbox').length

	useEffect(() => {
		setUser2(User.get())
	}, [])

	useEffect(() => {
		console.log('user2 is : ', user2)
		setAccount(async () => (await ApiService.get(`fairymailer/getAccount`, user2.jwt)).data.user.account)
	}, [user2])

	useEffect(() => {
		console.log('account from useEffect is : ', account)
		getCampaigns()
	}, [account])

	useEffect(() => {
		setFilteredCampaigns(campaigns.filter((campaign) => campaign.status === 'sent'))
	}, [campaigns])

	const updateSearchTerm = async (search) => {
		setSearchTerm(search)

		// if (search.length) {
		// let account = await ApiService.get(`fairymailer/getAccount`, user2.jwt)
		// account = account.data.user.account

		let outboxfilter = selectedCampaignType == 'outbox' ? '&filters[date][$notNull]=true' : selectedCampaignType == 'drafts' ? '&filters[date][$null]=true' : ''

		let resp = await ApiService.get(
			`fairymailer/getCampaigns?filters[name][$contains]=${search}&filters[account]=${account?.id}&filters[status]=${
				selectedCampaignType == 'outbox' ? 'draft' : selectedCampaignType == 'drafts' ? 'draft' : selectedCampaignType
			}${outboxfilter}&populate[recp_groups][populate][subscribers][count]=true&pagination[pageSize]=100&pagination[page]=1`,
			user2.jwt
		)
		console.log('cmps from search are : ', resp)

		setCampaigns(resp.data.data)

		// this.setState({ campaigns: resp.data.data, meta: resp.data.meta })
		// }
	}
	const getCampaigns = async (page = 1) => {
		try {
			console.log('user is getCampaigns : ', user2.jwt)

			// let account = await ApiService.get(`fairymailer/getAccount`, user2.jwt)
			// account = account.data.user.account
			// console.log('account is : ', account)

			// if (account) {
			// 	setAccount(account)
			// 	setDomainVerified(account.domain_verified)
			// 	setEmailVerified(account.email_verified)
			// 	setDkimVerified(account.dkim_verified)
			// }

			// let outboxfilter = selectedCampaignType == 'outbox' ? '&filters[date][$notNull]=true' : selectedCampaignType == 'draft' ? '&filters[date][$null]=true' : ''
			// let resp = await ApiService.get(
			// 	`fairymailer/getCampaigns?filters[account]=${account.id}&filters[status]=${
			// 		selectedCampaignType == 'outbox' ? 'draft' : selectedCampaignType
			// 	}${outboxfilter}&sort[sent_at]=desc&populate[recp_groups][populate][subscribers][count]=true&pagination[pageSize]=${itemsPerPage}&pagination[page]=${page}`,
			// 	user.jwt
			// )
			let resp = await ApiService.get(
				`fairymailer/getCampaigns?filters[account]=${account.id}&sort[sent_at]=desc&populate[recp_groups][populate][subscribers][count]=true&pagination[pageSize]=${itemsPerPage}&pagination[page]=${page}`,
				user2.jwt
			)
			console.log('cmps', resp)
			setCampaigns(resp.data.data)
		} catch (error) {
			console.error(error)
		}
	}

	return (
		<>
			<div className="fm-page-wrapper">
				<Sidemenu />
				<div className="fm-page-container">
					<PageHeader user={user} account={account} />
					<div className="page-name-container">
						<div className="page-name">Campaigns</div>
						<Button icon={'Plus'} type="action">
							New Campaign
						</Button>
					</div>
					<div className="filters-container">
						<div className="row" style={{ marginBottom: '1rem' }}>
							<ButtonGroup
								value="sent"
								options={[
									{ value: 'sent', label: `Sent (${totalCampaignsSent})` },
									{ value: 'draft', label: `Draft (${totalCampaignsDraft})` },
									{ value: 'outbox', label: `Outbox(${totalCampaignsOutBox})` },
									// { value: 'all', label: 'Templates (4)' },
								]}
								onChange={(value) => {
									console.log('the value is : ', value)
									switch (value) {
										case 'sent':
											setSelectedCampaignType('sent')
											setFilteredCampaigns(campaigns.filter((campaign) => campaign.status === 'sent'))
											break
										case 'draft':
											setSelectedCampaignType('draft')
											setFilteredCampaigns(campaigns.filter((campaign) => campaign.status === 'draft'))
											break
										case 'outbox':
											setSelectedCampaignType('outbox')
											setFilteredCampaigns(campaigns.filter((campaign) => campaign.status === 'outbox'))
											break
									}
								}}
							></ButtonGroup>
						</div>
						<div className="row d-flex content-space-between">
							<InputText
								onChange={(e) => updateSearchTerm(e.target.value)}
								style={{ width: '85%' }}
								placeholder="Search Campaign"
								label="Search Campaign"
								hasError={false}
								errorMessage="Name must be at least 3 characters long."
							/>
							<Button type="secondary" icon={'Filters'}>
								Filters
							</Button>
						</div>
					</div>

					<div className="">
						<CampaignsTable campaigns={campaignsTableData} />
					</div>
				</div>
			</div>
		</>
	)
}

export default Campaigns
