import React, { useEffect, useState } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import './DataTable.scss'
import Pagination from '../Pagination'
import Dropdown from '../Dropdown'
import Checkbox from '../Checkbox'

const CampaignsTable = () => {
	const [campaigns, setCampaigns] = useState([
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'User-friendly transitional pricing structure',
			recipients: 39121,
			opens: '65%',
			clicks: '93%',
			type: 'SMS',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synergistic tangible groupware',
			recipients: 25946,
			opens: '40%',
			clicks: '68%',
			type: 'Social Media',
			date: '2025-01-01',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Front-line even-keeled encryption',
			recipients: 36302,
			opens: '21%',
			clicks: '76%',
			type: 'Email',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Re-contextualized regional intranet',
			recipients: 45039,
			opens: '84%',
			clicks: '83%',
			type: 'Email',
			date: '2025-01-07',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered secondary firmware',
			recipients: 44327,
			opens: '6%',
			clicks: '8%',
			type: 'SMS',
			date: '2025-01-06',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Multi-tiered logistical matrices',
			recipients: 27215,
			opens: '53%',
			clicks: '41%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Configurable heuristic Graphical User Interface',
			recipients: 48929,
			opens: '89%',
			clicks: '54%',
			type: 'Social Media',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Fully-configurable methodical encryption',
			recipients: 18191,
			opens: '92%',
			clicks: '24%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Synchronised background parallelism',
			recipients: 17750,
			opens: '14%',
			clicks: '77%',
			type: 'Email',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Extended bi-directional workforce',
			recipients: 12643,
			opens: '73%',
			clicks: '87%',
			type: 'SMS',
			date: '2025-01-09',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Managed 24/7 functionalities',
			recipients: 10436,
			opens: '32%',
			clicks: '49%',
			type: 'Push Notification',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Reduced cohesive system engine',
			recipients: 39408,
			opens: '17%',
			clicks: '33%',
			type: 'Social Media',
			date: '2025-01-05',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Optional reciprocal flexibility',
			recipients: 36710,
			opens: '96%',
			clicks: '81%',
			type: 'Push Notification',
			date: '2025-01-08',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Devolved impactful task-force',
			recipients: 40386,
			opens: '81%',
			clicks: '63%',
			type: 'Email',
			date: '2025-01-13',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Robust discrete throughput',
			recipients: 18697,
			opens: '28%',
			clicks: '34%',
			type: 'SMS',
			date: '2025-01-02',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Sharable user-facing matrices',
			recipients: 41662,
			opens: '35%',
			clicks: '59%',
			type: 'Push Notification',
			date: '2025-01-11',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Triple-buffered incremental interface',
			recipients: 47389,
			opens: '48%',
			clicks: '21%',
			type: 'Social Media',
			date: '2025-01-12',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Distributed human-resource solution',
			recipients: 26709,
			opens: '64%',
			clicks: '88%',
			type: 'Email',
			date: '2025-01-03',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Function-based directional toolset',
			recipients: 31396,
			opens: '25%',
			clicks: '75%',
			type: 'SMS',
			date: '2025-01-10',
			actions: 'Actions Component Placeholder',
		},
		{
			image: 'https://i.imgur.com/1Xh6g2b_d.webp?maxwidth=760&fidelity=grand',
			name: 'Decentralized maximized knowledge user',
			recipients: 21871,
			opens: '71%',
			clicks: '52%',
			type: 'Push Notification',
			date: '2025-01-04',
			actions: 'Actions Component Placeholder',
		},
	])
	const [selectedCampaigns, setSelectedCampaigns] = useState([])

	const [currentPage, setCurrentPage] = useState(1)
	const rowsPerPage = 5

	const handlePageChange = (page) => {
		setCurrentPage(page)
	}

	const dropdownOptions = [
		{ value: 'option1', label: 'Option 1' },
		{ value: 'option2', label: 'Option 2' },
		{ value: 'option3', label: 'Option 3' },
	]
	const handleLeftClick = () => {
		alert('Left action triggered!')
	}

	const startIndex = (currentPage - 1) * rowsPerPage
	const endIndex = startIndex + rowsPerPage
	const paginatedData = campaigns.slice(startIndex, endIndex)

	useEffect(() => {
		console.log('selected campagins : ', selectedCampaigns)
	}, [selectedCampaigns])

	const actionsBodyTemplate = () => {
		return (
			<div>
				<Dropdown withDivider={true} icon={'Plus'} options={dropdownOptions} onLeftClick={handleLeftClick}>
					Report
				</Dropdown>
			</div>
		)
	}

	return (
		// <div>
		<>
			<DataTable value={paginatedData} paginator={false} selection={selectedCampaigns} onSelectionChange={(e) => setSelectedCampaigns(e.value)} dataKey="name" rowClassName={() => 'p-table-row'}>
				<Column
					body={(rowData) => (
						<div style={{ position: 'relative' }}>
							{/* Checkbox in the Top-Left Corner */}
							<div style={{ position: 'absolute', top: '10px', left: '5px' }}>
								<Checkbox
									checked={selectedCampaigns.some((campaign) => campaign.name === rowData.name)}
									onChange={(e) => {
										if (e) {
											setSelectedCampaigns((prev) => [...prev, rowData])
										} else {
											setSelectedCampaigns((prev) => prev.filter((campaign) => campaign.name !== rowData.name))
										}
									}}
								/>
							</div>
							{/* Image */}
							<img src={rowData.image} alt={rowData.name} style={{ width: '88px', height: '88px' }} />
						</div>
					)}
					header={() => (
						<Checkbox
							checked={selectedCampaigns.length === paginatedData.length && selectedCampaigns.length > 0}
							onChange={(e) => {
								if (e) {
									setSelectedCampaigns([...paginatedData])
								} else {
									setSelectedCampaigns([])
								}
							}}
						/>
					)}
					headerStyle={{ width: '80px' }}
				/>
				<Column field="name" header="Name" />
				<Column field="recipients" header="Recipients" />
				<Column field="opens" header="Opens" />
				<Column field="clicks" header="Clicks" />
				<Column field="type" header="Type" />
				<Column field="date" header="Date" />
				<Column header="Actions" body={actionsBodyTemplate} />
			</DataTable>
			<Pagination currentPage={1} totalResults={campaigns.length} resultsPerPage={10} onChange={handlePageChange} />
			{/* </div> */}
		</>
	)
}

export default CampaignsTable
